website/__init__.py
from flask import Flask, session, redirect, url_for
from pymongo import MongoClient
from os import path, mkdir

client = MongoClient()
db = client.Contractor 

app = Flask(__name__, static_url_path='/static')
app.config['SECRET_KEY'] = 'eigeinsonriuosvnirosjvsoe' 
upload_folder = 'website/static/images/'
if not path.exists(upload_folder):
  mkdir(upload_folder)
app.config['MAX_CONTENT_LENGTH'] = 25 * 1024 * 1024
app.config['UPLOAD_FOLDER'] = upload_folder

from .views import views
from .auth import auth
from .post import post
from .edit import edit

app.register_blueprint(views, url_prefix='/')
app.register_blueprint(auth, url_prefix='/auth/')
app.register_blueprint(post, url_prefix='/post/')
app.register_blueprint(edit, url_prefix='/edit/')


def create_app():

  return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from bson.objectid import ObjectId

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
  if 'username' in session:
    return redirect(url_for('views.home'))
  else:
    if request.method == 'POST':
      data = request.form
      username = data.get('username')
      password = data.get('password')
      checked_user = db.users.find_one({'username' : username})
      if checked_user:
        if check_password_hash(checked_user['password'], password):
          flash('Logged in successfully.', category='success')
          session["username"] = username
          return redirect(url_for('views.home'))
        else:
          flash('Incorrect password. Try again.', category='error')
      else:
        flash('Email does not exist in our records.', category='error')
    return render_template('login.html')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
  if 'username' in session:
    return redirect(url_for('views.hom'))
  else:
    if request.method == 'POST':
      data = request.form
      username = data.get('username')
      password = data.get('password')
      print(password)
      password_confirm = data.get('password_confirm')
      print(password_confirm)
      email = data.get('email')
      name = data.get('name')
      account = data.get('account')
      location = data.get('location')
      bio = data.get('bio') 
      check_username = db.users.find_one({'username' : username})
      check_email = db.users.find_one({'email' : email})
      if check_username:
        flash('username already exists', category='error')
      elif check_email: 
        flash('Email already exists.', category='error')
      elif len(username) < 6 or len(username) > 14:
        flash('username must be between 6 & 14 charactors.', category='error')
      elif len(password) < 6 or len(password) > 14:
        flash('passwird must be between 6 & 14 charactors.', category='error')
      elif password != password_confirm:
        flash('passwords do not match.', category='error')
      elif len(name) < 4:
        flash('name must be greater than 4 charactors.', category='error')
      else: 
        hashed_password = generate_password_hash(password, method='sha256')
        new_user = {
          'username': username,
          'password': hashed_password,
          'email': email,
          'name': name,
          'account': account,
          'location': location,
          'bio': bio,
          'photo_list': [],
          'photo_count': 0,
          'downloads': [],
          'downloads_count': 0,
          'edit_list':[],
          'edit_count': 0,
          'followers': [],
          'follower_count': 0,
          'following': [],
          'follwering_count': 0,
          'created_at': datetime.now()
        }
        db.users.insert_one(new_user)
        current_user = db.users.find_one({'username' : username})
        flash('Account has been created.', category='success')
        session['username'] = username
        return redirect(url_for('views.home'))
  return render_template('signup.html')

@auth.route('/logout')
def logout():
  if 'username' in session:
    session.pop('username', None)
  return redirect(url_for('auth.login'))

@auth.route('/admin/delete/user/<user_id>')
def delete_user(user_id):
  db.users.remove({'_id' : ObjectId(user_id)})
  return redirect(url_for('auth.admin_home'))
  
@auth.route('/admin/delete/post/<post_id>')
def delete_post(post_id):
  db.posts.remove({'_id' : ObjectId(post_id)})
  return redirect(url_for('auth.admin_home'))

@auth.route('/admin')
def admin_home():
  all_users = db.users.find()
  all_posts = db.posts.find()
  return render_template('admin.html', all_users=all_users, all_posts=all_posts)

website/views.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from . import db
from bson.objectid import ObjectId

views = Blueprint('views', __name__)

@views.route('/')
def home():
  if 'username' in session:
    username = session['username']
    current_user = db.users.find_one({'username': session['username']})
    feed = []
    current_user_following = current_user['following']
    for follower in current_user_following:
      following_photos = follower['photo_list']
      for photo in following_photos:
        feed.insert(0,photo)
      following_edits = follower['edit_list']
      for photo in following_edits:
        feed.insert(0,photo)
    print(feed)
    return render_template('user_feed.html', feed=feed)
  else:
    return redirect(url_for('auth.login'))

@views.route('/profile', methods=(['GET']))
def profile():
  if 'username' in session:
    loggedInUser = db.users.find_one({'username': session['username']})
    return render_template('profile.html', loggedInUser=loggedInUser)
  else:
    return redirect(url_for('auth.login'))

# TODO: Update the update_profile html file. 
  # not rendering correct information into the form fields
  # need to complete the form processing
  # check how to make sure the correct account type is displayed and selected
  # should redirect to home
@views.route('/profile/edit', methods=['GET', 'POST'])
def profile_update():
  if 'username' in session:
    loggedInUser = db.users.find_one({'username': session['username']})
    if request.method == 'POST':
      pass
    else:
      return render_template('update_profile.html', loggedInUser=loggedInUser)
  else:
    return redirect(url_for('auth.login'))

@views.route('/photos', methods=['GET'])
def user_photos():
  if 'username' in session:
    all_photos = db.posts.find({'author': session['username'], 'is_original': True})
    return render_template('user_photos.html', all_photos=all_photos)
  else:
    return redirect(url_for('auth.login'))

@views.route('/edits', methods=['GET'])
def user_edits():
  if 'username' in session:
    all_edits = db.posts.find({'author': session['username'], 'is_original': False})
    return render_template('user_edits.html', all_edits=all_edits)
  else:
    return redirect(url_for('auth.login'))

@views.route('/downloads', methods=['GET'])
def user_downloads():
  if 'username' in session:
    current_user = db.users.find_one({'username': session['username']})
    all_downloads = current_user['downloads']
    return render_template('user_downloads.html', all_downloads=all_downloads)
  else:
    return redirect(url_for('auth.login'))

@views.route('/search', methods=['GET', 'POST'])
def search():
  if 'username' in session:
    if request.method == 'POST':
      data = request.form
      search_term = data.get('search')
      search_results = db.users.find({'username' : {'$regex' : search_term}})
      return render_template('user_search.html', search_results=search_results)
    else:
      return render_template('search.html')
  else:
    return redirect(url_for('auth.login'))

@views.route('/follow/<user_id>', methods=['GET'])
def follow_user(user_id):
  if 'username' in session:
    following_user = db.users.find_one({'_id': ObjectId(user_id)})
    db.users.update({ 'username' : session['username']}, {'$push': {'following': following_user}})
    db.users.update({ 'username' : session['username']}, {'$inc': {'follwering_count': 1}})
    return redirect(url_for('views.home'))
  else:
    return redirect(url_for('auth.login'))

def sortFeed(e):
  return e['created_at']

website/templates/admin.html
{% extends 'base.html' %}

{% block title %} Admin Panel {% endblock %}

{% block navbar %}
<a class="nav-item nav-link" id="login" href="/">Home</a>
<a class="nav-item nav-link" id="signUp" href="/auth/login">Login</a>
{% endblock %}

{% block content %}

{% for user in all_users %}
  <p>{{ user.username }}</p>
  <p>{{ user.photo_list }}</p>
  <p>{{ user.photo_count }}</p>
  <p>{{ user.downloads }}</p>
  <p>{{ user.downloads_count }}</p>
  <p>{{ user.edit_list }}</p>
  <p>{{ user.edit_count }}</p>
  <p>{{ user.following }}</p>
  <p>{{ user.follwering_count }}</p>
  <a href={{ url_for('auth.delete_user', user_id=user._id )}}>DELETE USER</a>
{% endfor %}

{% for post in all_posts %}
  <p>{{ post.image_name }}</p>
  <p>{{ post.caption }}</p>
  <p>{{ post.location }}</p>
  <p>{{ post.likes_count }}</p>
  <a href={{ url_for('auth.delete_post', post_id=post._id )}}>DELETE POST</a>
{% endfor %}

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>{% block title %}Home{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/styles.css') }}">
  </head>
  <body class="container">
    <div class="row">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">

            {% block navbar %}
            {% endblock %}

          </div>
        </div>
      </nav>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        {% if category == 'error' %}

        <div class="alert alert-danger alter-dismissable" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>

        {% else %}

        <div class="alert alert-success" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>

        {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %} {% endblock %}
  
    <script src="index.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> 
  </body>
</html>

website/templates/create_edit.html
{% extends 'base.html' %}

{% block title %} Create Post {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/"><img style="height: 24px;" src={{ url_for('static', filename='fotos-logo.png' ) }}/></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}

<form actions="/edit/upload" enctype="multipart/form-data" method="POST">
  <div class="form-group">
    <label>UPLOAD EDIT</label>
  </div>
  <div class="form-group">
    <label for="photo">PHOTO</label>
    <input type="file" class="form-control" name="photo" id="photo" aria-describedby="photo" placeholder="Select Photo">
    <small id="emailHelp" class="form-text text-muted">Max file size is 15MB.</small>
  </div>
  <div class="form-group">
    <label for="image_name">TITLE</label>
    <input type="text" class="form-control" name="image_name" id="image_name" placeholder="Enter Title">
  </div>
  <div class="form-group">
    <label for="caption">CAPTION</label>
    <input type="text" class="form-control" name="caption" id="caption" placeholder="Enter Caption">
  </div>
  <div class="form-group">
    <label for="location">LOCATION</label>
    <input type="text" class="form-control" name="location" id="location" placeholder="Enter Location">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div class="row">
  <div class="col-4">
    <div class="card p-8">
      <a></a>
        <img src={{ url_for('static', filename='images/' + original_post.filename ) }}/>
      </a>
      <div style="display: flex; align-items: center; justify-content: space-between;">
        <div>
          <p style="padding-top: 8px;">@{{ original_post.author }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/create_post.html
{% extends 'base.html' %}

{% block title %} Create Post {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/"><img style="height: 24px;" src={{ url_for('static', filename='fotos-logo.png' ) }}/></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}

<form actions="/post/upload" enctype="multipart/form-data" method="POST">
  <div class="form-group">
    <label>UPLOAD POST</label>
  </div>
  <div class="form-group">
    <label for="photo">PHOTO</label>
    <input type="file" class="form-control" name="photo" id="photo" aria-describedby="photo" placeholder="Select Photo">
    <small id="emailHelp" class="form-text text-muted">Max file size is 25MB.</small>
  </div>
  <div class="form-group">
    <label for="image_name">TITLE</label>
    <input type="text" class="form-control" name="image_name" id="image_name" placeholder="Enter Title">
  </div>
  <div class="form-group">
    <label for="caption">CAPTION</label>
    <input type="text" class="form-control" name="caption" id="caption" placeholder="Enter Caption">
  </div>
  <div class="form-group">
    <label for="location">LOCATION</label>
    <input type="text" class="form-control" name="location" id="location" placeholder="Enter Location">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block navbar %}
<a class="nav-item nav-link" id="signUp" href="/auth/signup">Signup</a>
{% endblock %}

{% block content %}
<div class="pt-12">
  <form actions="/auth/login" enctype="multipart/form-data" method="POST">
    <div class="form-group">
      <label>LOGIN</label>
    </div>
    <div class="form-group pt-12">
      <label for="username">USERNAME</label>
      <input type="text" class="form-control" name="username" id="username" aria-describedby="username" placeholder="Enter Username">
    </div>
    <div class="form-group">
      <label for="password">PASSWORD</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block title %} PROFILE {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/"><img style="height: 24px;" src={{ url_for('static', filename='fotos-logo.png' ) }}/></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/profile">PROFILE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}

<p>{{ loggedInUser.profile_pic }}</p>
<h1>{{ loggedInUser.username }}</h1>
<p>{{ loggedInUser.following }}</p>
<p>{{ loggedInUser.followers }}</p>
<p>{{ loggedInUser.email }}</p>
<p>{{ loggedInUser.name }}</p>
<p>{{ loggedInUser.location }}</p>
<p>{{ loggedInUser.bio }}</p>
<p>{{ loggedInUser.photo_list }}</p>
<p>{{ loggedInUser.edit_list }}</p>

{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %} Create Post {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/"><img style="height: 24px;" src={{ url_for('static', filename='fotos-logo.png' ) }}/></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}

<form actions="/search" method="POST">
  <div class="form-group">
    <label for="search">SEARCH</label>
    <input type="text" class="form-control" name="search" id="search" aria-describedby="search" placeholder="Search Username">
  </div>
  <button type="submit" class="btn btn-primary">SEARCH</button>
</form>

{% endblock %}

website/templates/signup.html
{% extends 'base.html' %}

{% block title %} SIGN UP {% endblock %}

{% block navbar %}
<a class="nav-item nav-link" id="login" href="/auth/login">Login</a>
{% endblock %}

{% block content %}

<!-- <form actions="/auth/signup" method="POST">
  <header>Sign Up</header>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" placeholder="Enter Username"/>
    <label for="password">Password</label>
    <input type="password" for="password" name="password" placeholder="Enter Password"/>
    <label for="password-confirm">Confirm Password</label>
    <input type="password" for="password-confirm" name="password-confirm" placeholder="Confirm Password"/>
    <label for="email">Email</label>
    <input type="email" for="email" name="email" placeholder="Enter Email"/>
    <label for="name">Name</label>
    <input type="text" for="name" name="name" placeholder="Enter Name"/>
    <label for="account">Account</label>
    <select name="account">
      <option value="photographer">Photographer</option>
      <option value="videographer">Videographer</option>
      <option value="editor">Editr</option>
      <option value="designer">Designer</option>
    </select>
    <label for="bio">Bio</label>
    <input type="text" for="bio" name="bio" placeholder="Enter Bio"/>
    <label for="location">Location</label>
    <input type="text" for="location" name="location" placeholder="Enter City, State"/>
    <input type="submit" name="submit" value="Sign Up"/>
  </div>
</form> -->

<form actions="/auth/signup" enctype="multipart/form-data" method="POST">
  <div class="form-group">
    <label>SIGNUP</label>
  </div>
  <div class="form-group">
    <label for="username">USERNAME</label>
    <input type="text" class="form-control" name="username" id="username" aria-describedby="username" placeholder="Enter Username">
  </div>
  <div class="form-group">
    <label for="password">PASSWORD</label>
    <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
  </div>
  <div class="form-group">
    <label for="password_confirm">CONFIRM PASSWORD</label>
    <input type="password" class="form-control" name="password_confirm" id="password_confirm" placeholder="Confirm Password">
  </div>
  <div class="form-group">
    <label for="email">EMAIL</label>
    <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
  </div>
  <div class="form-group">
    <label for="name">NAME</label>
    <input type="text" class="form-control" name="name" id="name" placeholder="Enter Name">
  </div>
  <div class="form-group">
    <label for="bio">BIO</label>
    <input type="text" class="form-control" name="bio" id="bio" placeholder="Enter Bio">
  </div>
  <div class="form-group">
    <label for="location">LOCATION</label>
    <input type="text" class="form-control" name="location" id="location" placeholder="Enter Location">
  </div>
  <div class="form-group">
    <label for="account">ACCOUNT TYPE</label>
    <select id="account" class="form-control">
      <option value="photographer" selected>PHOTOGRAPHER</option>
      <option value="videographer" >VIDEOGRAPHER</option>
      <option value="editor" >EDITOR</option>
      <option value="designer" >DESIGNER</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

website/templates/update_profile.html
{% extends 'base.html' %}

{% block title %} UPDATE PROFILE {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/profile">PROFILE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}

<form actions="/auth/signup" method="POST">
  <header>UPDATE PROFILE </header>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" value={{ loggedInUser.username }}/>
    <label for="current-password">Current Password</label>
    <input type="password" for="password" name="current-password" defaultValue="Enter Current Password"/>
    <label for="new-password">New Password</label>
    <input type="password" for="password" name="new-password" defaultValue="Enter New Password"/>
    <label for="password-confirm">Confirm Password</label>
    <input type="password" for="password-confirm" name="password-confirm" defaultValue="Confirm Password"/>
    <label for="email">Email</label>
    <input type="email" for="email" name="email" value={{ loggedInUser.email }}/>
    <label for="name">Name</label>
    <input type="text" for="name" name="name" value={{ loggedInUser.name }}/>
    <label for="account">Account</label>
    <select name="account">
      <option value="photographer">Photographer</option>
      <option value="videographer">Videographer</option>
      <option value="editor">Editr</option>
      <option value="designer">Designer</option>
    </select>
    <label for="bio">Bio</label>
    <input type="text" for="bio" name="bio" value={{ loggedInUser.bio }}/>
    <label for="location">Location</label>
    <input type="text" for="location" name="location" value={{ loggedInUser.location }}/>
    <input type="submit" name="submit" value="Update Profile"/>
  </div>
</form>

{% endblock %}

website/templates/user_search.html
{% extends 'base.html' %}
{% block title %} HOME {% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/"><img style="height: 24px;" src={{ url_for('static', filename='fotos-logo.png' ) }}/></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/">FEED</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">PHOTOS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/edits">EDITS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/downloads">DOWNLOADS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/search">SEARCH</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/auth/logout">LOGOUT</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock %}

{% block content %}
  {% for user in search_results %}
    <div>
      <p>{{ user.username }}</p>
      <p>{{ user.email }}</p>
      <p>{{ user.bio }}</p>
      <a href={{ url_for('views.follow_user', user_id=user._id) }}>Follow</a>
    </div>
  {% endfor %}
{% endblock %}